"""Tests for credlens.release.staging (Fase 11A section 10) - the
read-only staging dry-run plan. Every git operation here runs inside an
isolated `tmp_path` repository."""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from credlens.release.staging import StagingPlanError, dry_run_stage, write_staging_plan


def _init_git_repo(root: Path) -> None:
    subprocess.run(["git", "init", "-q"], cwd=root, check=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=root, check=True)
    subprocess.run(["git", "config", "user.name", "Test"], cwd=root, check=True)


def _commit_all(root: Path, message: str) -> None:
    subprocess.run(["git", "add", "-A"], cwd=root, check=True)
    subprocess.run(["git", "commit", "-q", "-m", message], cwd=root, check=True)


def _staged_names(root: Path) -> str:
    return subprocess.run(
        ["git", "diff", "--cached", "--name-only"],
        cwd=root,
        capture_output=True,
        text=True,
        check=True,
    ).stdout


class TestDryRunStage:
    def test_reports_what_would_be_added_without_touching_the_index(self, tmp_path: Path) -> None:
        _init_git_repo(tmp_path)
        (tmp_path / "a.txt").write_text("x", encoding="utf-8")
        _commit_all(tmp_path, "init")
        (tmp_path / "src").mkdir()
        (tmp_path / "src" / "new.py").write_text("VALUE = 1\n", encoding="utf-8")

        result = dry_run_stage(["src/new.py"], repo_root=tmp_path)

        assert "src/new.py" in result.would_add
        assert result.index_untouched is True
        assert _staged_names(tmp_path).strip() == ""

    def test_refuses_to_run_against_an_already_dirty_index(self, tmp_path: Path) -> None:
        _init_git_repo(tmp_path)
        (tmp_path / "a.txt").write_text("x", encoding="utf-8")
        _commit_all(tmp_path, "init")
        (tmp_path / "b.txt").write_text("staged already", encoding="utf-8")
        subprocess.run(["git", "add", "b.txt"], cwd=tmp_path, check=True)

        with pytest.raises(StagingPlanError, match="dirty index"):
            dry_run_stage(["a.txt"], repo_root=tmp_path)

        # Clean up the staged file so this test doesn't leak state.
        subprocess.run(["git", "reset"], cwd=tmp_path, check=True)

    def test_batches_many_paths_without_exceeding_command_line_limits(self, tmp_path: Path) -> None:
        _init_git_repo(tmp_path)
        (tmp_path / "a.txt").write_text("x", encoding="utf-8")
        _commit_all(tmp_path, "init")
        (tmp_path / "src").mkdir()
        many_paths = []
        for i in range(450):  # > 2x the internal batch size
            path = tmp_path / "src" / f"module_{i}.py"
            path.write_text(f"VALUE = {i}\n", encoding="utf-8")
            many_paths.append(f"src/module_{i}.py")

        result = dry_run_stage(many_paths, repo_root=tmp_path)

        assert len(result.would_add) == 450
        assert result.index_untouched is True


class TestRenderAndWriteStagingPlan:
    def test_plan_lists_included_excluded_and_review_sections(self, tmp_path: Path) -> None:
        _init_git_repo(tmp_path)
        (tmp_path / "src").mkdir()
        (tmp_path / "src" / "module.py").write_text("VALUE = 1\n", encoding="utf-8")
        (tmp_path / "coverage.json").write_text('{"totals": {}}', encoding="utf-8")
        _commit_all(tmp_path, "init")

        path, inventory = write_staging_plan(tmp_path)

        assert path == tmp_path / "reports" / "release" / "staging_plan.txt"
        text = path.read_text(encoding="utf-8")
        assert "Files to INCLUDE" in text
        assert "Files to EXCLUDE" in text
        assert "Files requiring HUMAN REVIEW" in text
        assert "src/module.py" in text
        assert "coverage.json" in text
        assert "git add ." not in text.lower().replace("never generated by 'git add .'", "")
        assert inventory.fingerprint in text

    def test_render_without_git_dry_run_still_produces_a_full_plan(self, tmp_path: Path) -> None:
        _init_git_repo(tmp_path)
        (tmp_path / "README.md").write_text("# x\n", encoding="utf-8")
        _commit_all(tmp_path, "init")

        path, _inventory = write_staging_plan(tmp_path, run_git_dry_run=False)
        text = path.read_text(encoding="utf-8")
        assert "git add --dry-run verification" not in text

    def test_never_uses_add_dash_a_or_add_dot(self) -> None:
        import inspect

        import credlens.release.staging as staging_module

        source = inspect.getsource(staging_module)
        assert '"add", "-A"' not in source
        assert '"add", "."' not in source

    def test_writing_the_plan_never_touches_the_real_index(self, tmp_path: Path) -> None:
        _init_git_repo(tmp_path)
        (tmp_path / "a.py").write_text("x = 1\n", encoding="utf-8")
        _commit_all(tmp_path, "init")
        (tmp_path / "b.py").write_text("y = 2\n", encoding="utf-8")

        write_staging_plan(tmp_path)

        assert _staged_names(tmp_path).strip() == ""


@pytest.mark.slow
class TestRealRepoStagingPlan:
    def test_real_repo_plan_generates_without_touching_the_index(self) -> None:
        before = _staged_names(Path.cwd())
        assert before.strip() == "", "real repo index must be clean before this test runs"

        path, inventory = write_staging_plan(Path.cwd())
        try:
            assert path.is_file()
            assert len(inventory.included) > 0
            assert len(inventory.excluded) > 0
        finally:
            after = _staged_names(Path.cwd())
            assert after.strip() == ""
