"""Gate B - tracked-but-ephemeral index cleanup (Fase 11B section 11).

Fase 11A's release inventory found 1,024 tracked files that are real,
accidentally-committed BYPRODUCTS of running tests/monitoring/coverage
locally - never release content:

- `reports/modeling/quarantine/*.manifest.json` (721 files) - one per
  local `credlens model`/test run that quarantined input rows.
- `reports/monitoring/alerts/*.json` (164 files) - one per local
  monitoring run that raised at least one alert.
- `reports/monitoring/runs/RUN_*/run.json` (138 files) - one per local
  monitoring run invocation. Deliberately EXCLUDES `reports/monitoring/
  runs/BATCHSET_REF_MODEL_behavioral_default_v1/batch_manifest.json`,
  a genuine, load-bearing reference fixture `run_monitoring()`/
  `run_detection_evaluation()` read as an INPUT - not ephemeral output,
  and must stay tracked (see `_RUNS_REFERENCE_PREFIX`).
- `coverage.json` (1 file) - regenerated by every `pytest --cov-
  report=json` invocation.

This module only READS the index (`git ls-files`, `git ls-files -s`,
`git cat-file`) to build a manifest of what's there and why it's
ephemeral - it never removes anything itself. Actual removal
(`git rm --cached`, never a physical delete) is a separate, explicit
step (`execute_cleanup`) gated on an already-written, human-reviewable
manifest, exactly as Fase 11B section 11.4 requires.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

CLEANUP_MANIFEST_PATH = Path("reports/release/tracked_cleanup_manifest.json")
CLEANUP_MANIFEST_SCHEMA_VERSION = 1

# Windows CreateProcess has a real command-line length ceiling (see
# `credlens.release.staging`'s identical constant) - every batch git
# subprocess call in this module respects it.
_BATCH_SIZE = 200

# The one path under `reports/monitoring/runs/` that must NEVER be
# proposed for removal - see module docstring.
_RUNS_REFERENCE_PREFIX = "reports/monitoring/runs/BATCHSET_"


class CleanupManifestError(Exception):
    """Raised when the cleanup manifest cannot be built, or when the
    actually-tracked ephemeral paths no longer match an already-written
    manifest (a hard stop, per section 11.4 - never remove more, less,
    or different paths than were reviewed)."""


@dataclass(frozen=True)
class CleanupGroup:
    group_id: str
    git_prefix: str
    classification: str
    reason: str
    reproducible: bool
    reproducible_note: str
    gitignore_rule: str
    paths: tuple[str, ...]
    total_size_bytes: int
    aggregate_hash: str

    @property
    def quantity(self) -> int:
        return len(self.paths)

    def planned_command(self) -> str:
        """A description of the command `execute_cleanup` actually runs -
        NEVER a bare `git rm -r --cached -- {git_prefix}`, even when
        every current file under the prefix is ephemeral: that form
        would silently also remove any FUTURE non-ephemeral file added
        under the same prefix (exactly the mistake this group's own
        carve-out - e.g. `monitoring_runs` excluding `BATCHSET_*/` -
        exists to prevent). The real removal always targets this
        group's exact, individually-enumerated `paths`, batched."""
        if len(self.paths) == 1:
            return f"git rm --cached -- {self.paths[0]}"
        return f"git rm --cached -- <{self.quantity} explicit path(s) under {self.gitignore_rule}>"

    def to_dict(self) -> dict[str, Any]:
        return {
            "group_id": self.group_id,
            "path": self.git_prefix,
            "classification": self.classification,
            "quantity": self.quantity,
            "size_bytes": self.total_size_bytes,
            "hash": self.aggregate_hash,
            "reason": self.reason,
            "reproducible": self.reproducible,
            "reproducible_note": self.reproducible_note,
            "stays_on_disk": True,
            "gitignore_rule": self.gitignore_rule,
            "planned_command": self.planned_command(),
            "sample_paths": list(self.paths[:5]),
        }


@dataclass(frozen=True)
class CleanupManifest:
    schema_version: int
    groups: tuple[CleanupGroup, ...]

    @property
    def total_quantity(self) -> int:
        return sum(g.quantity for g in self.groups)

    @property
    def total_size_bytes(self) -> int:
        return sum(g.total_size_bytes for g in self.groups)

    @property
    def all_paths(self) -> tuple[str, ...]:
        return tuple(p for g in self.groups for p in g.paths)

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "n_groups": len(self.groups),
            "total_quantity": self.total_quantity,
            "total_size_bytes": self.total_size_bytes,
            "groups": [g.to_dict() for g in self.groups],
        }


def _batched(seq: list[str], size: int = _BATCH_SIZE) -> list[list[str]]:
    return [seq[i : i + size] for i in range(0, len(seq), size)]


def _tracked(repo_root: Path, prefix: str) -> list[str]:
    result = subprocess.run(
        ["git", "ls-files", prefix], cwd=repo_root, capture_output=True, text=True, check=True
    )
    return sorted(line for line in result.stdout.splitlines() if line)


def _blob_ids(repo_root: Path, paths: list[str]) -> dict[str, str]:
    ids: dict[str, str] = {}
    for batch in _batched(paths):
        if not batch:
            continue
        result = subprocess.run(
            ["git", "ls-files", "-s", "--", *batch],
            cwd=repo_root,
            capture_output=True,
            text=True,
            check=True,
        )
        for line in result.stdout.splitlines():
            meta, _tab, path = line.partition("\t")
            ids[path] = meta.split()[1]
    return ids


def _total_blob_size(repo_root: Path, blob_ids: list[str]) -> int:
    total = 0
    for batch in _batched(blob_ids):
        if not batch:
            continue
        result = subprocess.run(
            ["git", "cat-file", "--batch-check=%(objectsize)"],
            cwd=repo_root,
            input="\n".join(batch),
            capture_output=True,
            text=True,
            check=True,
        )
        total += sum(int(line) for line in result.stdout.split())
    return total


def _aggregate_hash(blob_ids: list[str]) -> str:
    return hashlib.sha256("\n".join(sorted(blob_ids)).encode("utf-8")).hexdigest()


# One entry per Fase 11B section 11.1 minimum-evaluated path. Only paths
# with concrete evidence (Fase 11A's inventory run) are listed here -
# "não inclua outros caminhos sem evidência" (section 11.1).
_GROUP_DEFINITIONS: tuple[tuple[str, str, str, str, bool, str, str], ...] = (
    (
        "modeling_quarantine",
        "reports/modeling/quarantine/",
        "temporary_excluded",
        "Per-run input-contract quarantine manifest, written every time "
        "`credlens model`/a test exercises quarantine handling - a local "
        "test/run byproduct, never reviewed or curated release content.",
        True,
        "Regenerated automatically the next time input rows are quarantined "
        "(any `credlens model` invocation or the relevant test suite).",
        "reports/modeling/quarantine/",
    ),
    (
        "monitoring_alerts",
        "reports/monitoring/alerts/",
        "temporary_excluded",
        "Per-run monitoring alert log, written every time a local "
        "monitoring run raises at least one alert - a local test/run "
        "byproduct, never reviewed or curated release content.",
        True,
        "Regenerated automatically by `credlens monitor run`/`evaluate` or "
        "the monitoring test suite.",
        "reports/monitoring/alerts/",
    ),
    (
        "monitoring_runs",
        "reports/monitoring/runs/",
        "temporary_excluded",
        "Per-invocation monitoring run record, written every time the "
        "monitoring pipeline executes - a local test/run byproduct, never "
        "reviewed or curated release content. Excludes the sibling "
        "BATCHSET_REF_MODEL_behavioral_default_v1/ directory, a genuine "
        "load-bearing reference fixture `run_monitoring()` reads as INPUT, "
        "not ephemeral output.",
        True,
        "Regenerated automatically by `credlens monitor run` or the monitoring test suite.",
        "reports/monitoring/runs/RUN_*/",
    ),
    (
        "coverage_json",
        "coverage.json",
        "temporary_excluded",
        "Machine-generated pytest coverage report (`--cov-report=json`), "
        "rewritten by every local test run - never curated release "
        "content (the release's own coverage acceptance evidence lives in "
        "reports/release/coverage_snapshot.json).",
        True,
        "Regenerated by any `pytest --cov-report=json` invocation, "
        "including `credlens release measure-coverage`.",
        "coverage.json",
    ),
)


def _group_paths(repo_root: Path, group_id: str, git_prefix: str) -> list[str]:
    tracked = _tracked(repo_root, git_prefix)
    if group_id == "monitoring_runs":
        return [p for p in tracked if not p.startswith(_RUNS_REFERENCE_PREFIX)]
    return tracked


def build_cleanup_manifest(repo_root: Path | None = None) -> CleanupManifest:
    repo_root = repo_root or Path.cwd()
    groups = []
    for (
        group_id,
        git_prefix,
        classification,
        reason,
        reproducible,
        reproducible_note,
        gitignore_rule,
    ) in _GROUP_DEFINITIONS:
        paths = _group_paths(repo_root, group_id, git_prefix)
        blob_id_map = _blob_ids(repo_root, paths)
        blob_ids = [blob_id_map[p] for p in paths]
        groups.append(
            CleanupGroup(
                group_id=group_id,
                git_prefix=git_prefix,
                classification=classification,
                reason=reason,
                reproducible=reproducible,
                reproducible_note=reproducible_note,
                gitignore_rule=gitignore_rule,
                paths=tuple(paths),
                total_size_bytes=_total_blob_size(repo_root, blob_ids),
                aggregate_hash=_aggregate_hash(blob_ids),
            )
        )
    return CleanupManifest(schema_version=CLEANUP_MANIFEST_SCHEMA_VERSION, groups=tuple(groups))


def write_cleanup_manifest(manifest: CleanupManifest, repo_root: Path | None = None) -> Path:
    repo_root = repo_root or Path.cwd()
    out_path = repo_root / CLEANUP_MANIFEST_PATH
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(manifest.to_dict(), indent=2) + "\n", encoding="utf-8")
    return out_path


@dataclass(frozen=True)
class CleanupExecutionResult:
    dry_run: bool
    removed_paths: tuple[str, ...]
    index_diff_matches_plan: bool


def execute_cleanup(
    manifest: CleanupManifest, repo_root: Path | None = None, *, dry_run: bool = True
) -> CleanupExecutionResult:
    """Removes exactly `manifest.all_paths` from the git INDEX only
    (`git rm --cached`, never bare `git rm`) - the files stay on disk
    untouched. Refuses (raises `CleanupManifestError`) if the currently
    tracked ephemeral paths have drifted from what the manifest was
    built against, or if anything outside the plan ends up staged -
    section 11.4's explicit safety requirements."""
    repo_root = repo_root or Path.cwd()
    planned = set(manifest.all_paths)

    current: set[str] = set()
    for group_id, git_prefix, *_rest in _GROUP_DEFINITIONS:
        current.update(_group_paths(repo_root, group_id, git_prefix))
    if current != planned:
        missing = planned - current
        extra = current - planned
        raise CleanupManifestError(
            "Tracked ephemeral paths have drifted since the manifest was built - "
            f"refusing to proceed. missing={len(missing)} extra={len(extra)}"
        )

    if dry_run:
        return CleanupExecutionResult(
            dry_run=True, removed_paths=tuple(sorted(planned)), index_diff_matches_plan=True
        )

    before_status = subprocess.run(
        ["git", "diff", "--cached", "--name-status"],
        cwd=repo_root,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    if before_status.strip():
        raise CleanupManifestError(
            "Refusing to run git rm --cached against an already-dirty index "
            "(git diff --cached --name-status is non-empty) - resolve this first."
        )

    for batch in _batched(sorted(planned)):
        if not batch:
            continue
        subprocess.run(
            ["git", "rm", "--cached", "--quiet", "--", *batch],
            cwd=repo_root,
            capture_output=True,
            text=True,
            check=True,
        )

    for path in planned:
        if not (repo_root / path).is_file():
            raise CleanupManifestError(
                f"'{path}' was removed from disk by git rm --cached - this must never "
                "happen (--cached was not effective); aborting."
            )

    after_status = subprocess.run(
        ["git", "diff", "--cached", "--name-status"],
        cwd=repo_root,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    staged_paths = set()
    for line in after_status.splitlines():
        _status, _tab, path = line.partition("\t")
        staged_paths.add(path.strip())
    if staged_paths != planned:
        raise CleanupManifestError(
            "git diff --cached --name-status does not exactly match the planned "
            f"removals - refusing to leave this unverified. unexpected={staged_paths - planned!r} "
            f"missing={planned - staged_paths!r}"
        )

    return CleanupExecutionResult(
        dry_run=False, removed_paths=tuple(sorted(planned)), index_diff_matches_plan=True
    )
