"""Read-only staging dry-run plan (Fase 11A section 10).

Produces `reports/release/staging_plan.txt`, an explicit, deterministic
list of exactly which paths a real publication would `git add`, which it
would deliberately leave out (and why), and which need a human decision
first - all derived from `credlens.release.inventory.build_release_
inventory` and verified with `git add --dry-run`, which reports what
WOULD be staged without ever touching the index (confirmed by this
module's own tests: `git diff --cached --name-only` stays empty before
and after). Never `git add .` / `git add -A` - only explicit, named
paths, exactly as Fase 11A section 10 requires.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from credlens.release.inventory import InventoryEntry, ReleaseInventory, build_release_inventory

STAGING_PLAN_PATH = Path("reports/release/staging_plan.txt")

# Windows CreateProcess has a real command-line length ceiling; batching
# keeps every `git add --dry-run` invocation well under it regardless of
# how many files the release ends up including.
_DRY_RUN_BATCH_SIZE = 200


class StagingPlanError(Exception):
    """Raised when the staging dry-run plan cannot be produced or
    verified read-only."""


@dataclass(frozen=True)
class StagingDryRunResult:
    would_add: tuple[str, ...]
    index_untouched: bool


def _git_diff_cached_names(repo_root: Path) -> str:
    result = subprocess.run(
        ["git", "diff", "--cached", "--name-only"],
        cwd=repo_root,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def dry_run_stage(paths: list[str], *, repo_root: Path) -> StagingDryRunResult:
    """Confirms, via `git add --dry-run` (read-only, never modifies the
    index), exactly which of `paths` git would stage. Verifies the index
    is unchanged both before and after - raises `StagingPlanError` rather
    than silently proceeding if this repo's git somehow behaves
    differently."""
    before = _git_diff_cached_names(repo_root)
    if before.strip():
        raise StagingPlanError(
            "Refusing to run a staging dry-run against an already-dirty index "
            "(git diff --cached --name-only is non-empty) - resolve this first."
        )

    would_add: list[str] = []
    for start in range(0, len(paths), _DRY_RUN_BATCH_SIZE):
        batch = paths[start : start + _DRY_RUN_BATCH_SIZE]
        if not batch:
            continue
        result = subprocess.run(
            ["git", "add", "--dry-run", "--", *batch],
            cwd=repo_root,
            capture_output=True,
            text=True,
            check=True,
        )
        for line in result.stdout.splitlines():
            # dry-run output lines look like: "add 'path/to/file'"
            if line.startswith("add '") and line.endswith("'"):
                would_add.append(line[len("add '") : -1])

    after = _git_diff_cached_names(repo_root)
    index_untouched = not before.strip() and not after.strip()
    if not index_untouched:
        raise StagingPlanError(
            "git add --dry-run appears to have modified the index - aborting. "
            f"before={before!r} after={after!r}"
        )
    return StagingDryRunResult(would_add=tuple(would_add), index_untouched=index_untouched)


def _format_size(num_bytes: int) -> str:
    size = float(num_bytes)
    for unit in ("B", "KB", "MB", "GB"):
        if size < 1024:
            return f"{size:.1f}{unit}"
        size /= 1024
    return f"{size:.1f}TB"


def render_staging_plan(inventory: ReleaseInventory, dry_run: StagingDryRunResult | None) -> str:
    included = sorted(inventory.included, key=lambda e: e.path)
    excluded = sorted(inventory.excluded, key=lambda e: e.path)
    review = sorted(inventory.needs_human_review, key=lambda e: e.path)
    total_included_bytes = sum(e.size_bytes for e in included)
    largest = sorted(included, key=lambda e: e.size_bytes, reverse=True)[:15]

    lines: list[str] = []
    lines.append("CredLens release staging plan (Fase 11A - read-only dry-run)")
    lines.append("=" * 70)
    lines.append(f"schema_version: {inventory.schema_version}")
    lines.append(f"release_inventory_fingerprint: {inventory.fingerprint}")
    lines.append("NEVER GENERATED BY 'git add .' / 'git add -A' - explicit named paths only.")
    lines.append("")
    lines.append(f"Files to INCLUDE ({len(included)}, {_format_size(total_included_bytes)} total):")
    lines.append("-" * 70)
    for entry in included:
        review_flag = " [NEEDS HUMAN REVIEW]" if entry.requires_human_review else ""
        lines.append(f"  {entry.path}  ({entry.classification}){review_flag}")

    lines.append("")
    lines.append(f"Files to EXCLUDE ({len(excluded)}):")
    lines.append("-" * 70)
    by_classification: dict[str, list[InventoryEntry]] = {}
    for entry in excluded:
        by_classification.setdefault(entry.classification, []).append(entry)
    for classification, entries in sorted(by_classification.items()):
        lines.append(f"  [{classification}] {len(entries)} file(s)")
        sample_reason = entries[0].reason
        lines.append(f"    reason: {sample_reason}")
        for entry in entries[:3]:
            lines.append(f"    e.g. {entry.path}")
        if len(entries) > 3:
            lines.append(f"    ... and {len(entries) - 3} more")

    lines.append("")
    lines.append(f"Files requiring HUMAN REVIEW before publication ({len(review)}):")
    lines.append("-" * 70)
    if not review:
        lines.append("  (none)")
    for entry in review:
        lines.append(f"  {entry.path}  ({entry.classification}) - {entry.reason}")

    lines.append("")
    lines.append(f"Largest {len(largest)} included files:")
    lines.append("-" * 70)
    for entry in largest:
        lines.append(f"  {_format_size(entry.size_bytes):>10}  {entry.path}")

    if dry_run is not None:
        lines.append("")
        lines.append("git add --dry-run verification:")
        lines.append("-" * 70)
        lines.append(f"  paths git confirms it would stage: {len(dry_run.would_add)}")
        lines.append(f"  index left untouched: {dry_run.index_untouched}")
        mismatch = {e.path for e in included} - set(dry_run.would_add)
        # Files already tracked with unchanged content produce no
        # "add '...'" dry-run line at all (nothing to add) - expected,
        # not a discrepancy; only genuinely missing/renamed paths matter.
        if mismatch:
            lines.append(
                f"  ({len(mismatch)} included path(s) already tracked and unchanged - "
                "git add --dry-run reports nothing for them, which is correct)"
            )

    lines.append("")
    return "\n".join(lines) + "\n"


def write_staging_plan(
    repo_root: Path | None = None, *, run_git_dry_run: bool = True
) -> tuple[Path, ReleaseInventory]:
    repo_root = repo_root or Path.cwd()
    inventory = build_release_inventory(repo_root)
    dry_run = None
    if run_git_dry_run:
        included_tracked_or_new = [e.path for e in inventory.included]
        dry_run = dry_run_stage(included_tracked_or_new, repo_root=repo_root)
    plan_text = render_staging_plan(inventory, dry_run)
    out_path = repo_root / STAGING_PLAN_PATH
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(plan_text, encoding="utf-8")
    return out_path, inventory


def staging_plan_summary(inventory: ReleaseInventory) -> dict[str, Any]:
    return {
        "n_included": len(inventory.included),
        "n_excluded": len(inventory.excluded),
        "n_needs_human_review": len(inventory.needs_human_review),
        "total_included_bytes": sum(e.size_bytes for e in inventory.included),
        "fingerprint": inventory.fingerprint,
    }
